#!/bin/sh

if [ "x$DEBUG" = "xyes" ]; then
    set -x
fi

fix_gcc() {
    local _gcc _v _cc1 _lib

    _gcc=$(which gcc 2>/dev/null)

    if [ "x$_gcc" = "x" ]; then
	return
    fi

    _v=$(gcc --version | grep GCC | awk '{print $3}')
    _cc1=$(find $APPDIR -name cc1 |grep gcc |grep $_v | head -n 1)

    if [ "x$_cc1" = "x" ]; then
	return
    fi
    
    _lib=$(find $APPDIR -name crt1.o |grep gcc |grep $_v | head -n 1)
    if [ "x$_lib" = "x" ]; then
	return
    fi
    
    COMPILER_PATH=$(dirname $_cc1)
    export COMPILER_PATH
    LIBRARY_PATH=$(dirname $_lib)
    export LIBRARY_PATH
}

set_pkg_path() {
    local _path _dir

    _dir="$APPDIR"
    if [ -z "$_dir" ]; then
	_dir="$XBUILD_DIR/.."
    fi

    _path=$(find $_dir -name "*.pc" -exec dirname {} \;| \
		sort |\
		uniq | \
		xargs echo | \
		sed -e 's/ /:/g')
    PKG_CONFIG_PATH="$_path"
    export PKG_CONFIG_PATH
}
PATH="$XBUILD_DIR:$PATH"
export PATH
# LD_LIBRARY_PATH="$XBUILD_DIR/../lib:$LD_LIBRARY_PATH"
# export LD_LIBRARY_PATH

if [ ! -z "$APPDIR" ]; then
    fix_gcc
fi

set_pkg_path

exec "$@"
