#!/bin/bash

APPDIR=$(dirname $(readlink -f "$0"))
PATH="$APPDIR/../bin:$PATH"
export PATH

APP_BASE_DIR=$APPDIR
export APP_BASE_DIR

if [ $# -lt 2 ]; then
    echo xbuild app args_for_app ...
    exit 1
fi

APP="$1"

shift 1

exec "$APP" "$@"

